//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Between_Us.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BetweenUsEntities : DbContext
    {
        public BetweenUsEntities()
            : base("name=BetweenUsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblFriendRequest> tblFriendRequests { get; set; }
        public virtual DbSet<tblFriend> tblFriends { get; set; }
        public virtual DbSet<tblPost> tblPosts { get; set; }
        public virtual DbSet<tblPostLiker> tblPostLikers { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
